//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purevision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalProfile
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int PropertyId { get; set; }
        public string PropertyValue { get; set; }
        public string PropertyText { get; set; }
        public int Visibility { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
        public int UpdatedByUserId { get; set; }
        public System.DateTime ArchivedOnDate { get; set; }
        public int ArchivedByUserId { get; set; }
        public string ExtendedVisibility { get; set; }
    
        public virtual People People { get; set; }
        public virtual ProfileProperty ProfileProperty { get; set; }
    }
}
