// <auto-generated />
namespace Purevision.Web.DataContexts.PurevisionMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddPersonBookkeepingEnumsX7_allowNulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPersonBookkeepingEnumsX7_allowNulls));
        
        string IMigrationMetadata.Id
        {
            get { return "201502260105255_AddPersonBookkeepingEnumsX7_allowNulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
