//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purevision.Web.Models.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.BusinessProfiles = new HashSet<BusinessProfile>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public int Id { get; set; }
        public int PrincipleOwnerUserId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<BusinessProfile> BusinessProfiles { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
