//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purevision.Web.Models.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public List()
        {
            this.Lists = new HashSet<List>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Text { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Level { get; set; }
        public int SortOrder { get; set; }
        public int DefinitionId { get; set; }
        public string Description { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> ArchivedOnDate { get; set; }
        public Nullable<int> ArchivedByUserId { get; set; }
    
        public virtual ICollection<List> Lists { get; set; }
        public virtual List List1 { get; set; }
    }
}
