//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purevision.Web.Models.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.People = new HashSet<People>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> ArchivedOnDate { get; set; }
        public Nullable<int> ArchivedByUserId { get; set; }
    
        public virtual ICollection<People> People { get; set; }
        public virtual Business Businesses { get; set; }
    }
}
