//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purevision.Web.Models.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileProperty
    {
        public ProfileProperty()
        {
            this.BusinessProfiles = new HashSet<BusinessProfile>();
            this.ClientProfiles = new HashSet<PersonalProfile>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public int DataType { get; set; }
        public string Default { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public int Length { get; set; }
        public bool Required { get; set; }
        public string Validation { get; set; }
        public int Order { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public Nullable<System.DateTime> ArchivedOnDate { get; set; }
        public Nullable<int> ArchivedByUserID { get; set; }
        public Nullable<int> DefaultVisibility { get; set; }
        public bool ReadOnly { get; set; }
    
        public virtual ICollection<BusinessProfile> BusinessProfiles { get; set; }
        public virtual ICollection<PersonalProfile> ClientProfiles { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
